import fs from "node:fs";
import path from "node:path";
import { projectAgentforgeDir } from "../config/settings.js";
import type { ProjectScan } from "./projectScanner.js";

/**
 * Project + user memory. /init writes AGENTFORGE.md; the agent loop injects
 * its contents into the system prompt so the model stays project-aware.
 */
export class MemoryManager {
  constructor(private cwd: string) {}

  projectMemoryPath(): string {
    return path.join(projectAgentforgeDir(this.cwd), "AGENTFORGE.md");
  }

  projectMemoryExists(): boolean {
    return fs.existsSync(this.projectMemoryPath());
  }

  async initProjectMemory(scan: ProjectScan): Promise<string> {
    const dir = projectAgentforgeDir(this.cwd);
    fs.mkdirSync(path.join(dir, "commands"), { recursive: true });
    fs.mkdirSync(path.join(dir, "skills"), { recursive: true });
    fs.mkdirSync(path.join(dir, "agents"), { recursive: true });

    const ignorePath = path.join(this.cwd, ".agentforgeignore");
    if (!fs.existsSync(ignorePath)) {
      fs.writeFileSync(ignorePath, "node_modules\n.git\ndist\nbuild\n.env\n*.log\n");
    }

    const content = [
      "# AgentForge Project Memory",
      "",
      `Generated by /init on ${new Date().toISOString().slice(0, 10)}.`,
      "",
      "## Detected stack",
      `- Languages: ${scan.languages.join(", ") || "unknown"}`,
      `- Frameworks: ${scan.frameworks.join(", ") || "none detected"}`,
      `- Package manager: ${scan.packageManager || "n/a"}`,
      `- Git: ${scan.hasGit ? "yes" : "no"}`,
      "",
      "## Architecture notes",
      "(Edit this section with high-level design, key modules, and data flow.)",
      "",
      "## Style & conventions",
      "(Coding style, naming, testing preferences.)",
      "",
      "## Hard rules",
      "- Never commit secrets or .env files.",
      "- Prefer small, focused diffs.",
      "",
    ].join("\n");

    const memPath = this.projectMemoryPath();
    fs.writeFileSync(memPath, content);
    return memPath;
  }

  loadProjectMemory(): string {
    const p = this.projectMemoryPath();
    if (!fs.existsSync(p)) return "";
    return fs.readFileSync(p, "utf-8");
  }

  loadIgnorePatterns(): string[] {
    const p = path.join(this.cwd, ".agentforgeignore");
    if (!fs.existsSync(p)) return ["node_modules", ".git", "dist", "build"];
    return fs
      .readFileSync(p, "utf-8")
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#"));
  }

  buildCombinedMemory(): string {
    const project = this.loadProjectMemory();
    if (!project) return "";
    return `## Project memory (AGENTFORGE.md)\n${project}`;
  }
}
